

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/blog_portal}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.mapper.sort-properties-alphabetically=false
# Replace the above line
logging.level.com.logging=info
logging.file.name=src/loggers/appLog.log
logging.pattern.file= %d [%level] %c [%t] %m %n
logging.pattern.console= %d [%level] %c [%t] %m %n

